---
version: '3.6'
services:

  builder:
    build: ./builder
    image: tramodana/builder
#    networks:
#      - default
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-cluster:9092
#    network_mode: host

  modeler:
    build: ./modeler
    image: tramodana/modeler
#    networks:
#      - default
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-cluster:9092

  query:
    build: ./query
    image: tramodana/query
    ports:
      - 5555:5555
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-cluster:9092

networks:
  default:
    external:
      name: bachelor-tramodana_default